version: "2.0"

volumes:

  mysql-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./mysql/data

  mongo-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./mongo/data

  minio-data: {}


services:

  mysql:
    image: mysql:8.0.34
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: streamserv
      MYSQL_PASSWORD: streamserv
      MYSQL_DATABASE: streamserv

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    environment:
      - MONGO_INITDB_DATABASE=StreamServ

  minio:
    image: minio/minio
    command: minio server --console-address ":9090" /data
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data


  trackdistributionservice:
    build:
      context: ../services/trackDistributionService
      dockerfile: ./Dockerfile
    image: streamserv/trackdistributionservice:0.0.2
    ports:
      - "5001:5000"
    environment:
      - MONGO_DSN=mongodb://StreamServ:StreamServ@127.0.0.1:27017
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_HOSTNAME=minio

  chatservice:
    build:
      context: ../services/chatService
      dockerfile: ./Dockerfile
    image: streamserv/chatservice:0.0.2
    links:
      - mysql:mysql
    ports:
      - "5002:5000"
    environment:
      - MYSQL_USER=streamserv
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=streamserv
      - MYSQL_DATABASE=streamserv
      - WS_PROTOCOL=ws
      - WS_HOST=localhost
      - WS_PORT=5002

  userservice:
    build:
      context: ../services/userService
      dockerfile: ./Dockerfile
    image: streamserv/chatservice:0.0.2
    links:
      - mysql:mysql
    ports:
      - "5003:5000"
    environment:
      - MYSQL_DSN='mysql+asyncmy://streamserv:streamserv@127.0.0.1/streamserv'
      - MAIL_USERNAME='streamserv@inbox.ru'
      - MAIL_PASSWORD='brBLU4Wmffrb8M2nrUXv'
      - MAIL_PORT=465
      - MAIL_SERVER='smtp.mail.ru'
