version: '2.21'

volumes:

  mysql-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./mysql/data

  mongo-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./mongo/data


services:

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      - MYSQL_USER: StreamServ
      - MYSQL_PASSWORD: StreamServ
      - MYSQL_DATABASE: StreamServ

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    environment:
      - MONGO_INITDB_DATABASE=StreamServ

  minio:
    image: quay.io/minio/minio:RELEASE.2023-02-10T18-48-39Z
    hostname: minio
    command: minio server --console-address ":9090" /data
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - data:/data


  trackdistributionservice:
    image: streamserv/trackdistributionservice
    ports:
      - "5000:5000"
    environment:
      - MONGO_DSN='mongodb://StreamServ:StreamServ@127.0.0.1:27017'
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_HOSTNAME=minio
    
